"""
Because users use all forms of spellings for each player, this file used as a repository of the different player name spellings.

This file is updated on a weekly basis to keep up with the new weird spellings.
"""


def player_name_vars():
    """create a dict with all possible variations of all player names"""
    player_var_names = {
        "Haaland": ["haaland", "hÃ¥land", "hauland", "halaand", "harlaand", "haaaland", "haalands", "haland", "erling"],
        "Trippier": ["trippier", "tripper", "trips", "tripps", "tripp", "trip", "kieran"],
        "Kane": ["kane"],
        "Ødegaard": ["odegaard", "Ã¸degaard", "odeegard", "odegard", "Ã¸gegÃ¥rd", "odeg", "degaard", "ode", "odergaard", "odergaad", "oder"],
        "Almirón": ["almiron", "almoron", "almirion", "almirÃ³n", "almerion", "almiroon", "almir"],
        "Toney": ["toney", "tony"],
        "Saka": ["saka"],
        "Rashford": ["rashford", "rash", "rashy", "rashfords", "rasford"],
        "De Bruyne": ["kdb", "bruyne", "kevin", "kev", "debryune", "debruyne"],
        "Pope": ["pope"],
        "Salah": ["salah"],
        "Martinelli": ["martinelli", "martineli", "nelli", "martenelli", "marti"],
        "Schär": ["schÃ¤r", "schar"],
        "Rodrigo": ["rodrigo"],
        "Raya": ["raya"],
        "Saliba": ["saliba", "sailiba", "sailba"],
        "Groß": ["groÃŸ", "gros", "gross", "grob"],
        "March": ["march"],
        "Burn": ["burn"],
        "Fernandes": ["bruno", "fernandes", "fernandez", "fernandez", "penandes"],
        "Gabriel": ["gabriel"],
        "Botman": ["botman", "bottman", "boatman"],
        "Trossard": ["trossard"],
        "White": ["white"],
        "Alisson": ["allison", "alisson"],
        "Mitrović": ["mitro", "mitrovic", "mitroviÄ‡"],
        "Henderson": ["henderson"],
        "Sá": ["sa"],
        "Ramsdale": ["ramsdale"],
        "Foden": ["foden"],
        "Højbjerg": ["hojbjerg", "jbjerg"],
        "Mee": ["mee"],
        "Xhaka": ["xhaka"],
        "Andreas": ["andreas"],
        "Maddison": ["maddison", "madison", "madder", "madisson", "maddisons", "madders", "maddi"],
        "Zaha": ["zaha"],
        "De Gea": ["gea", "ddg", "degea"],
        "Ederson": ["ederson"],
        "Barnes": ["barnes"],
        "Bowen": ["bowen"],
        "Eze": ["eze"],
        "Mount": ["mount"],
        "Ward-Prowse": ["prowse", "jwp"],
        "Eriksen": ["eriksen"],
        "Guaita": ["guaita"],
        "Leno": ["leno"],
        "Son": ["son"],
        "Cancelo": ["cancelo"],
        "Fabianski": [],
        "Gibbs-White": ["gibbs"],
        "Lloris": ["lloris"],
        "Willock": [],
        "Adams": [],
        "Bailey": ["bailey"],
        "Bernardo": [],
        "Castagne": ["castagne"],
        "Iwobi": ["iwobi"],
        "Firmino": ["firmino"],
        "Jensen": ["jensen"],
        "Jesus": ["jesus"],
        "Sánchez": [],
        "Ward": ["ward"],
        "Podence": [],
        "Watkins": ["watkins", "ollie", "watikins", "watkin", "wakins"],
        "Mac Allister": ["macallster", "allister", "macallister", "alister", "mac10", "allistar"],
        "Mahrez": ["mahrez"],
        "Bruno Guimarães": ["guimaraes"],
        "Neves": ["neves"],
        "Shaw": ["shaw"],
        "Billing": ["billing", "billimg"],
        "De Cordova-Reid": [],
        "Perišić": ["perisic", "persic"],
        "Dier": ["dier"],
        "Gray": [],
        "Olise": ["olise"],
        "Tielemans": [],
        "Arrizabalaga": ["kepa", "arrizabalaga", "keppa", "arriza", "ariza"],
        "Bentancur": ["bentancur"],
        "Dewsbury-Hall": ["kdh", "dewsbury"],
        "Havertz": ["havertz", "kai", "haverts", "havert"],
        "Johnson": ["johnson"],
        "Martínez": ["martinez", "lisandro", "martÃ­nez"],
        "Mbeumo": ["mbuemo", "mbeumo", "mbeuno"],
        "Meslier": ["meslier"],
        "Thiago Silva": ["thiago", "tsilva"],
        "Bernando Silva": ["silva"],
        "Wilson": ["wilson", "wilsons"],
        "Douglas Luiz": ["luiz"],
        "Pickford": ["pickford"],
        "Solanke": ["solanke"],
        "Ream": ["ream"],
        "Robertson": ["robertson", "robbo"],
        "Sterling": ["sterling", "pulisic"],
        "Tavernier": [],
        "Rodri": ["rodri"],
        "Struijk": ["struijk"],
        "Davies": ["davies"],
        "Gündogan": ["gundogan"],
        "Joelinton": ["joelinton"],
        "Buendía": ["buendia"],
        "Ings": ["ings"],
        "Palhinha": [],
        "Reed": [],
        "Van Dijk": ["vvd", "van"],
        "Wissa": [],
        "Zouma": ["zouma"],
        "Casemiro": ["casemiro", "cassemiro"],
        "Coady": [],
        "Harrison": ["harrison", "harison", "harrisson", "harisson"],
        "Kulusevski": ["kulusevski", "kulu"],
        "Alexander-Arnold": ["taa", "trent"],
        "Mitoma": ["mitoma", "mitomaâ€¦", "motoma", "mitimo", "mitomas"],
        "S.Longstaff": [],
        "Willian": ["willian"],
        "Henry": ["henry"],
        "Mings": ["mings"],
        "Rice": [],
        "Aaronson": [],
        "Kilman": ["kilman"],
        "Stones": ["stones"],
        "Darwin": ["darwin", "nunez", "darwins"],
        "Grealish": ["grealish", "jack"],
        "Janelt": [],
        "Partey": [],
        "Ramsey": [],
        "Dunk": ["dunk"],
        "Veltman": [],
        "Young": [],
        "Aurier": ["aurier"],
        "Dasilva": ["dasilva"],
        "Lerma": [],
        "Moore": [],
        "Awoniyi": [],
        "Bazunu": [],
        "Dalot": ["dalot"],
        "Konsa": ["konsa"],
        "Soucek": [],
        "Zinchenko": ["zinchenko", "zinchenco", "zinny"],
        "Jorginho": ["jorginho"],
        "Vardy": [],
        "Ayew": ["ayew"],
        "Benrahma": ["said", "benrama", "benrahma"],
        "Cucurella": ["cucurella", "cucu"],
        "Gomez": ["gomez"],
        "Koulibaly": ["koulibaly"],
        "Varane": ["varane"],
        "Lallana": [],
        "Mykolenko": ["mykolenko"],
        "Onana": [],
        "Amartey": ["amartey"],
        "Andersen": ["andersen"],
        "Edouard": ["edouard"],
        "Tarkowski": ["takowski", "tarkowski", "tark", "tarko", "tarkowkski", "tarkowsi", "tarkoski"],
        "Daka": [],
        "Emerson Royal": ["royal"],
        "Justin": [],
        "Perraud": ["perraud"],
        "Summerville": [],
        "Caicedo": [],
        "Mitchell": [],
        "Welbeck": ["danny"],
        "Akanji": ["akanji"],
        "Antonio": [],
        "Cook": [],
        "Estupiñán": ["estupian", "estu", "estupinan", "etsu", "estupiÃ±an", "eustupinan", "estupunian", "estipuian", "estupnian", "estup", "estupinian", "estupi", "estipinan", "etupinan", "estupinon", "estupin"],
        "Gordon": [],
        "Guéhi": ["guehi"],
        "Robinson": [],
        "Collins": [],
        "Cresswell": [],
        "Nketiah": ["nketiah", "nkehtia", "eddie", "nkeitah", "nkeitha", "nkethia", "nkethiah", "nketia"],
        "Schlupp": [],
        "Smith": [],
        "Tete": [],
        "Aké": [],
        "Aribo": [],
        "Dias": ["dias"],
        "Elliott": [],
        "Scamacca": [],
        "Álvarez": ["alvarez"],
        "Faes": ["faes"],
        "McNeil": ["mcneil"],
        "Moutinho": [],
        "Roca": [],
        "Sancho": ["sancho"],
        "A.Armstrong": [],
        "Antony": ["antony"],
        "Diop": [],
        "Luis Díaz": [],
        "Matheus": [],
        "Nørgaard": [],
        "Paquetá": [],
        "Anthony": [],
        "Pinnock": ["pinnock"],
        "Saint-Maximin": [],
        "Yates": [],
        "Azpilicueta": ["azpilicueta", "azpi"],
        "C.Doucouré": [],
        "Fornals": [],
        "Digne": ["digne"],
        "Malacia": ["malacia"],
        "McGinn": [],
        "Wood": [],
        "Chalobah": [],
        "Christie": [],
        "Doherty": ["doherty"],
        "Elyounoussi": [],
        "Kebano": [],
        "Kehrer": [],
        "Murphy": ["murphy"],
        "N.Williams": ["williams", "nico", "neco"],
        "Zemura": [],
        "Koch": [],
        "R.Sessegnon": [],
        "Webster": [],
        "Worrall": [],
        "Aït-Nouri": ["nouri"],
        "Fred": [],
        "Roerslev": [],
        "Adama": [],
        "Chilwell": ["chilwell", "chillwell", "chillwel", "chilwel", "chillewll", "chiwell"],
        "Fabinho": [],
        "Freuler": [],
        "Gueye": [],
        "Jonny": [],
        "Martial": ["martial"],
        "Walker-Peters": [],
        "Gallagher": ["gallagher"],
        "McKenna": [],
        "Romero": ["romero"],
        "Salisu": [],
        "Coufal": ["coufal"],
        "Lingard": [],
        "Semedo": ["semedo"],
        "Tosin": [],
        "Guedes": [],
        "Pulisic": [],
        "Cooper": [],
        "Ferguson": ["ferguson"],
        "Kamara": [],
        "Neto": ["neto"],
        "Ajer": [],
        "Coleman": ["coleman"],
        "Isak": ["isak"],
        "James": ["james", "reese", "reece"],
        "Kelly": [],
        "Kouyaté": [],
        "Kristensen": [],
        "S.Armstrong": [],
        "Tomiyasu": ["tomiyasu"],
        "Wan-Bissaka": ["wanbissaka", "awb"],
        "Boly": [],
        "Bueno": ["bueno", "beuno"],
        "Mepham": [],
        "Renan Lodi": ["lodi"],
        "Walker": ["walker"],
        "Carvalho": [],
        "Kovacic": [],
        "Lenglet": [],
        "Loftus-Cheek": [],
        "Maupay": ["maupay"],
        "Senesi": ["senesi"],
        "Soumaré": [],
        "Travers": [],
        "Ayling": ["ayling"],
        "Bamford": ["bamford"],
        "Cairney": ["cairney"],
        "Fábio Vieira": [],
        "Patterson": ["patterson", "padderson", "paterson"],
        "Richarlison": ["richarlison"],
        "Thiago": ["thiago"],
        "Calvert-Lewin": [],
        "Clyne": [],
        "Hwang": [],
        "Mendy": [],
        "Sinisterra": [],
        "Targett": [],
        "Tsimikas": [],
        "Vinícius": [],
        "Bissouma": [],
        "Cash": ["cash"],
        "Coutinho": [],
        "Dendoncker": [],
        "Greenwood": ["greenwood"],
        "Iheanacho": ["iheanacho", "nacho", "iheanaco"],
        "Lavia": [],
        "Milner": ["milner"],
        "O'Brien": [],
        "Tierney": [],
        "Zanka": [],
        "Aubameyang": [],
        "Broja": [],
        "Gnonto": ["gnonto", "gnoto", "gnotto"],
        "Dennis": [],
        "Djenepo": [],
        "Elanga": [],
        "Gelhardt": [],
        "Nelson": ["nelson"],
        "Ronaldo": [],
        "Surridge": [],
        "Bella-Kotchap": [],
        "Caleta-Car": [],
        "Garnacho": [],
        "Mangala": [],
        "Mateta": [],
        "Ndidi": [],
        "Pérez": [],
        "Toffolo": [],
        "Ziyech": [],
        "Baptiste": [],
        "Chamberlain": [],
        "Edozie": [],
        "Mara": [],
        "McTominay": [],
        "Onyeka": [],
        "Jansson": ["jansson"],
        "Laporte": ["laporte"],
        "Dawson": ["dawson"],
        "Llorente": [],
        "Praet": [],
        "Thomas": ["thomas"],
        "Colwill": [],
        "Diallo": [],
        "Maguire": ["maguire"],
        "Badiashile": ["badiashile"],
        "Lamptey": ["lamptey"],
        "Maitland-Niles": [],
        "Milivojevic": [],
        "Albrighton": [],
        "Emerson": ["emerson"],
        "Hickey": [],
        "Lewis": ["lewis", "rico"],
        "Lewis-Potter": [],
        "Lyanco": [],
        "Mina": [],
        "Downes": [],
        "Holgate": [],
        "Hughes": [],
        "Klich": [],
        "Lindelöf": [],
        "Ogbonna": [],
        "Traoré": [],
        "Chukwuemeka": [],
        "Evans": [],
        "Fraser": [],
        "Mwepu": [],
        "Stephens": [],
        "Toti": ["toti"],
        "A.Doucouré": [],
        "Bajcetic": ["bajcetic"],
        "Damsgaard": [],
        "Diego Costa": [],
        "Richards": [],
        "Sarmiento": [],
        "Aguerd": ["aguerd"],
        "Begović": [],
        "Bryan": [],
        "Fredericks": [],
        "Ghoddos": [],
        "Konaté": ["konate"],
        "Ake": ["ake"],
        "Matip": ["matip"],
        "Olsen": [],
        "Pearson": [],
        "Skipp": [],
        "Zakaria": [],
        "Anderson": [],
        "Colback": [],
        "Diogo Jota": ["jota", "diogo"],
        "Hall": [],
        "Jiménez": [],
        "Lucas Moura": [],
        "Palmer": [],
        "Rothwell": [],
        "Sambi": [],
        "Undav": [],
        "Van de Beek": [],
        "Wöber": [],
        "Keita": [],
        "Mbabu": [],
        "Niakhaté": [],
        "Rodák": [],
        "Rondón": [],
        "Sergio Gómez": [],
        "Stansfield": [],
        "Álex Moreno": ["moreno"],
        "Archer": [],
        "Dembélé": [],
        "Elneny": [],
        "Enciso": [],
        "Forshaw": [],
        "Gilmour": [],
        "Holding": ["holding"],
        "Jones": [],
        "Campbell": [],
        "Canós": [],
        "Cornet": [],
        "Gakpo": ["gakpo", "gapko"],
        "Garner": [],
        "Godfrey": [],
        "Kanté": [],
        "Lanzini": [],
        "Ouattara": ["ouattara", "ouatarra", "outarra", "outtara"],
        "Smith Rowe": [],
        "Stacey": [],
        "Bech": [],
        "Bednarek": [],
        "Chambers": [],
        "Cunha": ["cunha"],
        "Dervişoğlu": [],
        "Duffy": [],
        "Hennessey": [],
        "Hodge": [],
        "Larios": [],
        "Riedewald": [],
        "Spence": [],
        "Stanislas": [],
        "W.Fofana": ["fofana", "wesley"],
        "Weghorst": ["weghorst", "wegz"],
        "Diego Carlos": [],
        "Ebiowei": [],
        "Firpo": [],
        "Harris": [],
        "Phillips": [],
        "Sarr": [],
        "Shelvey": [],
        "Solomon": [],
        "Walcott": [],
        "Areola": ["areola"],
        "Augustinsson": [],
        "Biancone": [],
        "Cannon": [],
        "Cédric": [],
        "Dele": [],
        "Doak": [],
        "Forster": ["forster"],
        "Lemina": [],
        "Lowe": [],
        "Onomah": [],
        "Ritchie": [],
        "Romeu": [],
        "Sanson": [],
        "Scarpa": [],
        "Simms": [],
        "Söyüncü": [],
        "Van Hecke": [],
        "Vinagre": [],
        "Alcaraz": [],
        "Bevan": [],
        "Brunt": [],
        "Cafú": [],
        "Clark": [],
        "Coventry": [],
        "Danilo": [],
        "Drameh": [],
        "Francois": [],
        "Gyabi": [],
        "Hutchinson": [],
        "Kalajdžić": [],
        "Keane": [],
        "Krafth": [],
        "Kurzawa": [],
        "Lascelles": [],
        "Lembikisa": [],
        "Manquillo": [],
        "Marcondes": [],
        "Marquinhos": [],
        "Mateo Joseph": [],
        "Mighten": [],
        "Moran": [],
        "Mubama": [],
        "Mudryk": ["mudryk"],
        "Nwaneri": [],
        "Orsic": [],
        "Ozoh": [],
        "Redmond": [],
        "Ronan": [],
        "Sarabia": ["sarabia"],
        "Schade": [],
        "Tanganga": ["tangaga"],
        "Ablade": [],
        "Adrián": [],
        "Adu-Adjei": [],
        "Ahamada": [],
        "Allan": [],
        "Alonso": [],
        "Alzate": [],
        "Amad": [],
        "Ampadu": [],
        "Andrey Santos": [],
        "Sanchez": ["sanchez"],
        "André Gomes": [],
        "Arter": [],
        "Arthur": [],
        "Ashby": [],
        "Austin": [],
        "Ayari": [],
        "B.Williams": [],
        "Badé": [],
        "Bailly": [],
        "Balcombe": [],
        "Balmer": [],
        "Barkley": [],
        "Bate": [],
        "Bennett": [],
        "Benteke": [],
        "Bentley": [],
        "Bergwijn": [],
        "Bertrand": [],
        "Bettinelli": [],
        "Bidstrup": [],
        "Bishop": [],
        "Bogarde": [],
        "Branthwaite": [],
        "Braybrooke": [],
        "Bree": [],
        "Brooks": [],
        "Buonanotte": [],
        "Butland": [],
        "Butler-Oyedeji": [],
        "Caballero": [],
        "Carson": [],
        "Cavaleiro": [],
        "Chiquinho": [],
        "Choudhury": [],
        "Clarke": [],
        "Cox": [],
        "Cozier-Duberry": [],
        "Crama": [],
        "Cundle": [],
        "D.D.Fofana": [],
        "Dacosta Gonzalez": [],
        "Dale Taylor": [],
        "Dallas": [],
        "Danjuma": [],
        "Darlow": [],
        "Davis": [],
        "Delap": [],
        "Devine": [],
        "Dräger": [],
        "Dubravka": [],
        "Dummett": [],
        "Durán": [],
        "El Ghazi": [],
        "Enzo": ["enzo"],
        "Fabio Silva": [],
        "Felipe": [],
        "Fernández": [],
        "Finnigan": [],
        "Forss": [],
        "Furlong": [],
        "Gayle": [],
        "Gazzaniga": [],
        "Gbamin": [],
        "Godo": [],
        "Gomes": [],
        "Goode": [],
        "Goodman": [],
        "Griffiths": [],
        "Guilbert": [],
        "H.Davies": [],
        "H.Traorè": [],
        "Hammond": [],
        "Hause": [],
        "Heaton": [],
        "Hein": [],
        "Hendrick": [],
        "Hill": [],
        "Hinshelwood": [],
        "Hjelde": [],
        "Hudson-Odoi": [],
        "Humphreys": [],
        "Iqbal": [],
        "Iroegbunam": [],
        "Iversen": ["iverson", "iversen"],
        "Jakupović": [],
        "John": [],
        "Johnstone": [],
        "João Gomes": [],
        "Kadan Young": [],
        "Kamaldeen": [],
        "Karius": [],
        "Kelleher": [],
        "Kenedy": [],
        "Kesler Hayden": [],
        "Kiwior": [],
        "Klaesson": [],
        "Knight": [],
        "Knockaert": [],
        "Kongolo": [],
        "Kovár": [],
        "Kozłowski": [],
        "Kristiansen": [],
        "Kuol": [],
        "Laryea": [],
        "Lis": [],
        "Livramento": [],
        "Lolley": [],
        "Lukic": [],
        "Lyle Taylor": [],
        "Madueke": [],
        "Mainoo": [],
        "Marschall": [],
        "Masuaku": [],
        "Matthews": [],
        "Mbe Soh": [],
        "Mbete": [],
        "McArthur": [],
        "McAtee": [],
        "McAteer": [],
        "McCarthy": [],
        "McKennie": [],
        "Mills": [],
        "Moder": [],
        "Morgan": [],
        "Mosquera": [],
        "Muniz": [],
        "Nakamba": [],
        "Navas": ["navas"],
        "Nkounkou": [],
        "Ojeda": [],
        "Oko-Flex": [],
        "Onuachu": [],
        "Ortega": [],
        "Pablo Marí": [],
        "Panzo": [],
        "Parkes": [],
        "Parrott": [],
        "Payne": [],
        "Pedro Porro": ["porro", "poro", "pedro"],
        "Pellistri": [],
        "Perkins": [],
        "Perrone": [],
        "Philogene-Bidace": [],
        "Plain": [],
        "Plange": [],
        "Pollock": [],
        "Price": [],
        "Pépé": [],
        "R.Williams": [],
        "Rak-Sakyi": [],
        "Ramsay": [],
        "Randolph": [],
        "Raphinha": [],
        "Reguilón": [],
        "Ricardo": ["ricardo", "pereira", "perreira"],
        "Roberts": [],
        "Robles": [],
        "Rodney": [],
        "Rodon": [],
        "Rutter": [],
        "Sabitzer": [],
        "Sadi": [],
        "Samba": [],
        "Saydee": [],
        "Scarlett": [],
        "Scherpen": [],
        "Schmeichel": [],
        "Sekularac": [],
        "Semenyo": [],
        "Shackleton": [],
        "Shoretire": [],
        "Sinisalo": [],
        "Smallbone": [],
        "Smithies": [],
        "Sousa": [],
        "Souttar": [],
        "Steele": ["steele"],
        "Steffen": [],
        "Stevens": [],
        "Strakosha": [],
        "Tavares": [],
        "Tella": [],
        "Telles": [],
        "Tetê": [],
        "Thompson": [],
        "Torreira": [],
        "Townsend": [],
        "Trevitt": [],
        "Turner": [],
        "Turns": [],
        "Vale": [],
        "Valery": [],
        "Van den Berg": [],
        "Vestergaard": ["vestegaard", "vestergaard"],
        "Viña": [],
        "Vlasic": [],
        "Warrington": [],
        "Welch": [],
        "Wells-Morrison": [],
        "Werner": [],
        "Whitworth": [],
        "Wormleighton": [],
        "Xande Silva": [],
        "Yarmolyuk": [],
        "Zabarnyi": [],
        "Šarkić": [],
        "Tomkins": [],
        "João Félix": ["felix", "joao", "jaoa"],
    }

    return player_var_names
